#
# Copyright (c) 2013 Qualcomm Atheros, Inc.
#
# All Rights Reserved.
# Qualcomm Atheros Confidential and Proprietary.
#
# Makefile for Shortcut FE.
#

obj-m += shortcut-fe.o
obj-m += shortcut-fe-cm.o

shortcut-fe-objs := \
	sfe_ipv4.o

shortcut-fe-cm-objs := \
	sfe_cm.o

